### PR TITLE
geth 1.11 support

### PR DESCRIPTION
**Pull request by chappjc**
Resolves https://github.com/decred/dcrdex/issues/2135

The main changes are:
- a new `txpool` package where we get the `txpool.ErrAlreadyKnown` error
- the harness must start with ` --rpc.enabledeprecatedpersonal` since the test harness uses the deprecated built-in account for simplicity.  Will still must migrate to an external signer.

The dex-test server appears to be running fine with v1.11.4 as the highest priority provider.

### CODE REVIEW

**Comment by chappjc** [comment]
Server on simnet harness looks happy: `[TRC] ASSET[eth][RPC]: Healthy connections: [ws://localhost:38559 /home/user/dextest/eth/alpha/node/geth.ipc]`

Client's **simnet** wallet is functional:
image

ETH-funded orders accepted by server:

```
2023-03-21 16:49:31.558 [TRC] MKT: balance check for eth - 0xEaAcac3fE6c4682C00a7f8A19A471318115924ac: new qty = 3000000000, new lots = 2, new redeems = 0
2023-03-21 16:49:31.559 [TRC] MKT: (*DEXBalancer).CheckBalance: balance check for eth - 0xEaAcac3fE6c4682C00a7f8A19A471318115924ac: total qty = 3000000000, total lots = 2, total redeems = 0, redeemCosts = 0, required = 3069800000, bal = 72000000000, fee bal = 0
2023-03-21 16:49:31.559 [TRC] MKT: Received order afa23bfbfaee7ddab2a49e2bb4e1ed6b708e8c30ca319d25603fa98d63481805 at 2023-03-21 21:49:31.559 +0000 UTC
```

Interactive swaps working:

image

I had to use the 3m/6m lock times however since 30sec/1m gets revokes too easy.

**Comment by chappjc** [comment]
```
--- PASS: TestSimnetMultiRPCClient (33.47s)
PASS
ok  	decred.org/dcrdex/client/asset/eth	33.490s
```

Anyone up for the `simnet-trade-tests`?  :grin:

**Comment by chappjc** [comment]
server/asset/eth needed to be using the "beta" node with txpool api namespace, but that was unrelated to the geth 1.11 change:

```
$  go test -v -tags harness
2023-03-21 17:23:53.219 [DBG] T: API endpoints supported by ws://localhost:38559: eth:1.0 rpc:1.0 txpool:1.0
2023-03-21 17:23:53.219 [DBG] T: API endpoints supported by /home/jon/dextest/eth/alpha/node/geth.ipc: admin:1.0 clique:1.0 debug:1.0 engine:1.0 eth:1.0 les:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0
2023-03-21 17:23:53.220 [TRC] T: Healthy connections: [ws://localhost:38559 /home/jon/dextest/eth/alpha/node/geth.ipc]
=== RUN   TestBestHeader
--- PASS: TestBestHeader (0.00s)
=== RUN   TestHeaderByHeight
--- PASS: TestHeaderByHeight (0.00s)
=== RUN   TestBlockNumber
--- PASS: TestBlockNumber (0.00s)
=== RUN   TestSuggestGasTipCap
--- PASS: TestSuggestGasTipCap (0.00s)
=== RUN   TestSwap
--- PASS: TestSwap (0.00s)
=== RUN   TestTransaction
--- PASS: TestTransaction (0.00s)
=== RUN   TestAccountBalance
=== RUN   TestAccountBalance/eth
=== RUN   TestAccountBalance/token
--- PASS: TestAccountBalance (1.37s)
    --- PASS: TestAccountBalance/eth (0.68s)
    --- PASS: TestAccountBalance/token (0.69s)
=== RUN   TestMonitorHealth
2023-03-21 17:23:54.593 [INF] T: Not found error successfully propagated
Waiting for client health check...
2023-03-21 17:23:56.220 [ERR] T: Failed to get header from "ws://localhost:38559": client is closed
2023-03-21 17:23:56.221 [TRC] T: Healthy connections: [/home/jon/dextest/eth/alpha/node/geth.ipc]
2023-03-21 17:23:56.221 [WRN] T: Failing connections: [ws://localhost:38559]
2023-03-21 17:23:59.221 [ERR] T: Failed to get header from "ws://localhost:38559": client is closed
2023-03-21 17:23:59.221 [TRC] T: Healthy connections: [/home/jon/dextest/eth/alpha/node/geth.ipc]
2023-03-21 17:23:59.221 [WRN] T: Failing connections: [ws://localhost:38559]
Original clients: [ws://localhost:38559 /home/jon/dextest/eth/alpha/node/geth.ipc]
Updated clients: [/home/jon/dextest/eth/alpha/node/geth.ipc ws://localhost:38559]
--- PASS: TestMonitorHealth (5.00s)
PASS
ok  	decred.org/dcrdex/server/asset/eth	6.392s
```

**Review by JoeGruffins — APPROVED** [review]
> Anyone up for the simnet-trade-tests?

Are mostly passing... but I doubt their failure has anything to do with these changes.

Working well on simnet. Syncing testnet again to try out there.

**Comment by JoeGruffins** [comment]
actually one print from client I havn't seen before
```
WARN [03-22|15:10:51.783] Failed to watch keystore folder          path=/home/joe/.dexc/simnet/assetdb/eth/simnet/keystore err="no such file or directory"
```

**Comment by chappjc** [comment]
> actually one print from client I havn't seen before
> 
> ```
> WARN [03-22|15:10:51.783] Failed to watch keystore folder          path=/home/joe/.dexc/simnet/assetdb/eth/simnet/keystore err="no such file or directory"
> ```

Had also seen this.  I think it was on teardown of one of the tests.  You?
I recall assuming it was poorly coordinated shutdown where the folders were being removed before the node was fully stopped.

**Comment by JoeGruffins** [comment]
> Had also seen this. I think it was on teardown of one of the tests. You?

No, it seems to be just running dexc with these changes. It is also printing to stderr I think, rather than stdout.

**Comment by chappjc** [comment]
OK, this "Failed to watch keystore folder" error appears to be expected since https://github.com/ethereum/go-ethereum/commit/e34e540e4c6cfaae67543427f7c36bff1408fcaf

Just when checking for wallet existence in `client/asset/eth.(*Driver).Exists`, `accounts/keystore.NewKeyStore` does `(*KeyStore) init(keydir string)`, which checks the keystore dir and spews this error when it tries to start a "watcher" goroutine (I don't know why it thinks it's a good idea to do that for such an action) though.  Unfortunately there's no "ExistsKeyStore" function to use instead.

However, in `createWallet`, I think we should attempt to create the keystore folder first to avoid this error there.  Will attempt.

**Review by buck54321 — APPROVED** [review]

**Pull request merged**
