### PR TITLE
core: allow empty password to signify unencrypted wallet

### LINKED ISSUE #591: client: UX for unencrypted btc wallets
Currently, dexc expects an encrypted wallet and errors when attempting to unlock an unencrypted wallet.
Should tell the user their wallet is not encrypted, so omit the PW or encrypt the wallet yourself first.

This would require making the wallet password field optional, if dexc can successfully connect to and use an unencrypted wallet (without password ofc). Otherwise, keep wallet password field required and request users to encrypt their wallet before connecting their wallet to the dex client.

### PR DESCRIPTION
**Pull request by buck54321**
Resolves #591. Also enables some upgrades I want to make to the simnet harness.

### CODE REVIEW

**Comment by chappjc** [comment]
@JoeGruffins Would you be free to test this out?

**Review by JoeGruffins — COMMENTED** [review]
Simnet test panics:
```
$ go test -tags harness
2020-10-08 09:02:00.512 [INF] TEST: === SETUP
2020-10-08 09:02:00.513 [INF] DB: Upgrading database from version 0 to 1
2020-10-08 09:02:00.513 [INF] TEST: [client 1] core created
2020-10-08 09:02:00.513 [INF] CORE: started DEX client core
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x87c649]

goroutine 10 [running]:
decred.org/dcrdex/client/core.(*Core).Run(0x0, 0xbd5bc0, 0xc00002ca00)
        /home/joe/git/dcrdex/client/core/core.go:843 +0x69
decred.org/dcrdex/client/core.startClients.func1(0xc000010108, 0xbd5bc0, 0xc00002ca00)
        /home/joe/git/dcrdex/client/core/trade_simnet_test.go:115 +0x46
created by decred.org/dcrdex/client/core.startClients
        /home/joe/git/dcrdex/client/core/trade_simnet_test.go:114 +0x5ab
exit status 2
FAIL    decred.org/dcrdex/client/core   0.071s
```
It looks like this is in master, so please ignore.

**Review by JoeGruffins — APPROVED** [review]
Other than the simnet test looks great.

**Review by itswisdomagain — APPROVED** [review]
Looks good. Just a nit pick.

**Review by chappjc — APPROVED** [review]
All works as expected, except if you click "Lock" for an unencrypted wallet, it really does nothing but the page shows an "Unlock" button.

Unencrypted wallet (delta simnet):

image

After clicking "Lock":

image

When you refresh the page it's back to being unlocked (because it never really was locked).  Same effect as clicking Unlock (no prompt for password, just starts showing as unlocked).  Similarly, you can just navigate to /markets and it appears as unlocked.

**Pull request merged**
