### PR TITLE
multi: Use `any` instead of `interface{}` and fix polygon live test

### PR DESCRIPTION
**Pull request by ukane-philemon**
This changes our use of `interface{}` to `any` because it reads better and it's shorter and includes a minor fix for polygon multirpc live test.

### CODE REVIEW

**Review by martonp — APPROVED** [review]
Could you add `multirpc_live_test.go.go` to `run_tests.go` please?

**Comment by buck54321** [comment]
Nack on the `interface{} -> any` change. Go programmers know what an `interface{}` is, `any` is not some kind of standard replacement, and using `any` instead of `interface{}` just forces devs to look up the type definition.

**Comment by buck54321** [comment]
Oh. `any` is a standardized replacement. Hmm.

**Comment by ukane-philemon** [comment]
Okay. Let me know if you want the test fix in another PR.

**Review by JoeGruffins — APPROVED** [review]
Could be two prs but changes look fine to me.

**Review by buck54321 — APPROVED** [review]

**Pull request merged**
