### PR TITLE
client/btc: Use coin specific tx hashes.

### LINKED ISSUE #2327: client/zec: Sent transaction id does not exist.
Testing with zcash `v5.4.2` on both simnet and testnet when sending some amount the displayed txid does not show up when doing `getrawtransaction`. When checking the node with `listtransactions` it will also show a different txid for the amount sent. Trade txid swap/refund/redeem can be found so it appears to only be a problem with sends.

### PR DESCRIPTION
**Pull request by JoeGruffins**
closes #2327

### CODE REVIEW

**Review by chappjc — APPROVED** [review]
Good catch. There are so many gotchas with zcash and it's about to get trickier with https://github.com/decred/dcrdex/pull/2338
I wonder if we should make zec not a clone wallet any more.   This fix looks good though.

**Comment by chappjc** [comment]
I see a few more wrong hashes if you wanna add these:

```diff
diff --git a/client/asset/btc/btc.go b/client/asset/btc/btc.go
index e36a38649..21988027e 100644
--- a/client/asset/btc/btc.go
+++ b/client/asset/btc/btc.go
@@ -3109,7 +3109,7 @@ func accelerateOrder(btc *baseWallet, swapCoins, accelerationCoins []dex.Bytes,
        delete(btc.fundingCoins, newOutPoint(changeTxHash, changeVout))
 
        if newChange == nil {
-               return nil, signedTx.TxHash().String(), nil
+               return nil, btc.hashTx(signedTx).String(), nil
        }
 
        // Add the new change to the cache if needed. We check if
@@ -3137,7 +3137,7 @@ func accelerateOrder(btc *baseWallet, swapCoins, accelerationCoins []dex.Bytes,
 
        // return nil error since tx is already broadcast, and core needs to update
        // the change coin
-       return newChange, signedTx.TxHash().String(), nil
+       return newChange, btc.hashTx(signedTx).String(), nil
 }
 
 // AccelerationEstimate takes the same parameters as AccelerateOrder, but
@@ -5314,7 +5314,7 @@ func (btc *baseWallet) MakeBondTx(ver uint16, amt, feeRate uint64, lockTime time
                return nil, nil, fmt.Errorf("failed to sign bond tx: %w", err)
        }
 
-       txid := signedTx.TxHash()
+       txid := btc.hashTx(signedTx)
 
        signedTxBytes, err := serializeMsgTx(signedTx)
        if err != nil {
@@ -5326,7 +5326,7 @@ func (btc *baseWallet) MakeBondTx(ver uint16, amt, feeRate uint64, lockTime time
        }
 
        // Prep the redeem / refund tx.
-       redeemMsgTx, err := btc.makeBondRefundTxV0(&txid, 0, amt, bondScript, bondKey, feeRate)
+       redeemMsgTx, err := btc.makeBondRefundTxV0(txid, 0, amt, bondScript, bondKey, feeRate)
        if err != nil {
                return nil, nil, fmt.Errorf("unable to create bond redemption tx: %w", err)
        }
@@ -5339,7 +5339,7 @@ func (btc *baseWallet) MakeBondTx(ver uint16, amt, feeRate uint64, lockTime time
                Version:    ver,
                AssetID:    btc.cloneParams.AssetID,
                Amount:     amt,
-               CoinID:     toCoinID(&txid, 0),
+               CoinID:     toCoinID(txid, 0),
                Data:       bondScript,
                SignedTx:   signedTxBytes,
                UnsignedTx: unsignedTxBytes,
```

**Comment by chappjc** [comment]
Oh crud, also, `cfg.TxSerializer` needs to be used in `MakeBondTx` instead of `serializeMsgTx`.
ZEC has forced `baseWallet` to get a little out of hand.

**Comment by chappjc** [comment]
> Oh crud, also, `cfg.TxSerializer` needs to be used in `MakeBondTx` instead of `serializeMsgTx`. ZEC has forced `baseWallet` to get a little out of hand.

should work but haven't tried it:

```diff
diff --git a/client/asset/btc/btc.go b/client/asset/btc/btc.go
index 5ac495bef..b4b689780 100644
--- a/client/asset/btc/btc.go
+++ b/client/asset/btc/btc.go
@@ -5316,11 +5316,11 @@ func (btc *baseWallet) MakeBondTx(ver uint16, amt, feeRate uint64, lockTime time
 
        txid := signedTx.TxHash()
 
-       signedTxBytes, err := serializeMsgTx(signedTx)
+       signedTxBytes, err := btc.serializeTx(signedTx)
        if err != nil {
                return nil, nil, err
        }
-       unsignedTxBytes, err := serializeMsgTx(baseTx)
+       unsignedTxBytes, err := btc.serializeTx(baseTx)
        if err != nil {
                return nil, nil, err
        }
@@ -5330,7 +5330,7 @@ func (btc *baseWallet) MakeBondTx(ver uint16, amt, feeRate uint64, lockTime time
        if err != nil {
                return nil, nil, fmt.Errorf("unable to create bond redemption tx: %w", err)
        }
-       redeemTx, err := serializeMsgTx(redeemMsgTx)
+       redeemTx, err := btc.serializeTx(redeemMsgTx)
        if err != nil {
                return nil, nil, fmt.Errorf("failed to serialize bond redemption tx: %w", err)
        }
```

**Comment by JoeGruffins** [comment]
Applying chapp changes https://github.com/decred/dcrdex/compare/b7957ae597a98a656e6d20f231c3255167c73bcb..24a1b5a5988ba9b43ab907c905b9fb0b8a12cfef

**Pull request merged**
