### PR TITLE
dexclient: Add a terminal user interface

### LINKED ISSUE #38: client: CLI application
In addition to the [Core Client Components](https://github.com/decred/dcrdex/milestone/3) milesone issues, a command line interface (CLI) application needs to be created for the DEX client.

Work on this issue should **follow** development and testing of the core client components.

---

A suggestion I have for making the CLI app as interactive and intuitive as possible is to make use of **menus and a clear workflow**.  To this goal, one tool that I have had good luck with in dcrdata's `democlient` CLI for the `psclient` package is https://github.com/AlecAivazis/survey.

### PR DESCRIPTION
**Pull request by JoeGruffins**
closes #38 #80 

Add a tui that uses termdash.

So.... buttons...
<details close>
<summary>screen</summary>

initial

</details>

Navigation is done by the **tabs** across the top.
Under that is graphs/tables and other content that changes when pressing tabs on top
They are just placeholders at the moment

The console works a bit. Currently it understands two commands, quit and echo
You can also quit by pressing esc

### CODE REVIEW

**Comment by chappjc** [comment]
Let's replace the buttons with a menu item section, just a list like on the left of the grin UI linked previously.  Those buttons are just terrible looking, and tbh with just a keyboard, buttons don't make much sense.

**Comment by JoeGruffins** [comment]
@chappjc 
I like the buttons, but I won't fight for them, I guess.
So no buy or sell buttons either?
Should the tui be made with the assumption that there is no mouse? I didn't realize this.

**Comment by chappjc** [comment]
Right, no mouse.  The buttons designs in termdash are ridiculously big with those shadows.  We just need some menu items.

**Comment by chappjc** [comment]
As [@buck54321](https://github.com/decred/dcrdex/issues/38#issuecomment-557671752) stated, this does not need to be fancy since a proper GUI app will follow eventually.  This is strictly for console people, so no mouse.  In fact, this *could* be done with no UI panes at all, just prompts followed by dumped info, but I don't think that would be very pleasant.

**Comment by buck54321** [comment]
This is a nice start, but yeah, those buttons gotta go. Can you catch mouse events on text widgets?

I threw together a cartoon of what I'm envisioning. Is something like this possible @JoeGruffins?

image

**Comment by JoeGruffins** [comment]
@buck54321 thanks for graphic!

Should there also be an always present console?
Are there interactive widgets other than the menu and console, or are the charts and such just for viewing?
Should tab be used to navigate between widgets?

**Comment by chappjc** [comment]
Depends what you mean by console.  Definitely a text box for certain information that needs to be shown in response to certain actions.

I expect most of the widgets would be view only, except the top orders where it would be nice to select a price for the new order dialog.

**Comment by buck54321** [comment]
> Should there also be an always present console?

I think what you're asking is whether every "view" should have a widget to display general messaging to the user, and I think the short answer is no. Certainly there will be various elements that display the status of important operations, but I don't think we need to dictate that every view has a general-use notification widget visible. If it fits without crowding out other important elements, it can go in. It could also have it's own "view".  

> Are there interactive widgets other than the menu and console, or are the charts and such just for viewing?

Let's assume the charts are read-only, but order table rows can hopefully be selectable by keyboard and mouse, and will auto-populate the rate field in an order form, as @chappjc mentioned. Menu items likewise should be selectable by keyboard and mouse, if possible. 

> Should tab be used to navigate between widgets?

I would prefer arrows, but I don't know what all's possible. I'm thinking something sort of like "hot keys" in dcrdata (enable it in the hamburger menu), where a special border is used to indicate the focused element, and arrow keys or clicks can change which element has focus.

**Comment by chappjc** [comment]
I generally agree with what @buck54321 said, although I expect each view will need space for at a minimum one line of text or alerts.  Trying to imagine myself as a user of this CLI, I would expect the app would say when certain important things happen regardless of the view.  For example: connection lost, order X matched, redeem broadcasted for X, etc.  It's not reasonable to require a large box for a paragraph of text on each view, but I think we need a way to hint to the user what view they should look at when something important happens.  Otherwise I'd be bouncing between the "Swaps" view and whatever other view I was trying to use at the moment to see how my trades are coming along (did something go wrong, are the swaps progressing as intended, how many confirms until stage X, etc.).  Well, I'd still be doing that anyway but it would be much less frequent if important events somehow make their way onto a common view element.

**Comment by buck54321** [comment]
I think we'll have room for it everywhere. Maybe we can implement it in two styles. One feed with no interactions and only a few to a couple tens of lines. This simpler feed widget could be embedded in many different views. Then one widget for a notification view with more history available.

Ideally, I'd like to be able to see the application log output somewhere as well. Not sure how that fits into this picture.

**Comment by JoeGruffins** [comment]
I'm going to leave a debugging screen underneath for now.  It can easily be toggled with a flag later, i.e. run with --debug to view logs. Looking into the menus...

**Comment by JoeGruffins** [comment]
termdash did not have the needed menu or the ability to traverse widgets with arrow keys. I have added both of those features to joegruffins/termdash.  It seems I need to update my tags for the builds to work.

**Comment by chappjc** [comment]
If we're forking termdash, I suspect that means termdash is not what we need.  Maintaining a fork of termdash is something to be avoided.
Before we go down this road, let's look for just what we need:
- subdivided screen / panes
- Menu (rows of text that can be highlighted, selected, and bound to a function)
- interaction/navigation between panes

These are fairly simple features I think.  As for the menus, have we considered using survey within one of these panes (if none of these UI packages implement a menu like we need)?

**Comment by chappjc** [comment]
A text table and select widget seem to have been planned in termdash for sometime: https://github.com/mum4k/termdash/issues/5 https://github.com/mum4k/termdash/issues/105
Who knows why they never materialized.

termui has an interactive list: https://github.com/gizak/termui/blob/master/_examples/list.go
and "tab panes" with the ability to change focus: https://github.com/gizak/termui/blob/12333d6a7ed85fe9a2c6727cba7e9834ef8b7cf6/v3/widgets/tabs.go

**Comment by chappjc** [comment]
What might be possible for pane navigation is to do it at the application level.  By that I mean process key events and setting the context for commands in the app rather than finding a UI package that handles that all.  e.g. with termui, you'd do

```go
...activeList // is one of several lists in different Blocks
...
uiEvents := termui.PollEvents()
for {
	e := <-uiEvents
	switch e.ID {
	case "q", "<C-c>":
		// quit
		return
	case "j", "<Down>":
		activeList.ScrollDown()
	case "k", "<Up>":
		activeList.ScrollUp()
	case "<C-d>":
		// change activeList to list in a different pane
	case "<C-u>":
		// change activeList to list in a different pane
	case "<Home>":
		// reset or go to top of current list
	}
```

**Comment by chappjc** [comment]
gocui seems to have Views that may take focus.  https://godoc.org/github.com/jroimartin/gocui#Gui.SetCurrentView
Plus these views implement `io.ReaderWriter`, so you can do anything inside them (like run a survey).

**Comment by JoeGruffins** [comment]
I think termui is termdash minus about 300 commits. It is not as developed.
gocui's last commit is 2 years ago.
I don't think tview has graphs or animations at all.

I think my simple changes to termdash make it the best candidate, but I also agree that it may not be worth sustaining.  As the article you linked in the issue states, there just isn't a great tui written in go. If what you want is graphics, then web sounds good.  I will stop development on this barring more discussion.

**Comment by buck54321** [comment]
I've been playing with tview and it's pretty slick. It doesn't have mouse events, but whatever. It enables raw character drawing, so plots could be constructed too. I'll push something either today or tomorrow.

**Comment by chappjc** [comment]
A few points:
1. I don't like playing the bad guy, promise, no matter how it looks.
2. There's nothing wrong with forking a repo and taking owner ship of the code; it can be a very smart idea, especially if the upstream is mature or no longer developed or maintained.
3. My conclusion about termdash is purely based on the fact that it needed significant modifications to handle the tasks we needed done, which really aren't too specialized, I think.
4. I'm not particularly swayed toward one repo or another based on commit count or last commit date (although 2 years ago is seriously pushing it).  What does help me settle on a dependency is it's quality, suitability for the task, and how the API feels.  This really does take time to choose when there are a number of options.  We just have to play with them, read the docs, and decide how straightforward it would be to get the job done.  I went through a half dozen http multiplexers/routers back in the early days of dcrdata.  It it was frustrating, but very educational, and we settled on something that is extremely solid, modern, and easy to use (chi).  Either we be patient in this process too, or we start at a lower level (std library, or maybe tcell which BTW helps power tview) to get the job done with much more of our own code.  My hope is that we don't have to do that though.

**Comment by JoeGruffins** [comment]
@chappjc 
Ok!
All points understood, and I don't have a problem with any of them.

**Pull request closed without merging**
