### PR TITLE
dex/networks/eth: ETHSwapV0 testnet address

### PR DESCRIPTION
**Pull request by martonp**
ETHSwapV0 is on the Goerli Testnet.

### CODE REVIEW

**Comment by chappjc** [comment]
Very nice.  I see you submitted the source too https://goerli.etherscan.io/address/0xa7767db7335EEF856B9319e9c7A98abEA0B78b61#code

Out of curiosity, did you deploy from the geth console with `personal.sendTransaction` and a `data` field, or someother way like Ganache?

**Comment by martonp** [comment]
I used this website: https://www.myetherwallet.com/wallet/access. Once you connect metamask, there's an option to deploy a contract. You just have to copy paste the bytecode.

**Comment by JoeGruffins** [comment]
Will sync up my internal testnet node and try a swap.

**Comment by JoeGruffins** [comment]
The contract can be viewed here https://goerli.etherscan.io/address/0xa7767db7335EEF856B9319e9c7A98abEA0B78b61

The tx data looks exactly like ours except for the last 43 bytes:
`6fc27be9817e8d83ffc07058740023a0448eb04b78c71482f40677a13ee3a4f764736f6c63430008060033`
Any idea what it is?

Also awesome!

**Review by JoeGruffins — APPROVED** [review]
Are we locked into this as v0 now? I hope no, as maybe #1427 can still happen.

**Comment by chappjc** [comment]
I think it will be fine to change the v0 contract as long as it's not on mainnet.  Plus there are no public testnet servers on master that I'm aware of, so any testnet action will likely be trading with self (consistent "v0" contract") in a controlled setup.

That said, let's get v0 locked down ASAP.

Who's is doing https://github.com/decred/dcrdex/issues/1427?  Are you on that issue @JoeGruffins?

**Comment by chappjc** [comment]
Let's get https://github.com/decred/dcrdex/pull/1455 merged first and then we can update this.

**Comment by chappjc** [comment]
Can update with https://github.com/decred/dcrdex/pull/1455 merged

**Comment by JoeGruffins** [comment]
I guess need to submit a new tx? @martonp going to do it? I kinda messed up the original so can do it if you want me to.

**Comment by martonp** [comment]
It's ok, I can do it.

**Comment by martonp** [comment]
It's updated.

**Review by chappjc — APPROVED** [review]
Confirmed latest contract at https://goerli.etherscan.io/address/0xa483b6166dA8Da6748B29Af35f96C4F9388c456C#code

@martonp @JoeGruffins Looks like we might want to update our solc: https://goerli.etherscan.io/solcbuginfo?a=SignedImmutables
linked from our contract's code page

**Comment by JoeGruffins** [comment]
> Confirmed latest contract at https://goerli.etherscan.io/address/0xa483b6166dA8Da6748B29Af35f96C4F9388c456C#code
> 
> @martonp @JoeGruffins Looks like we might want to update our solc: https://goerli.etherscan.io/solcbuginfo?a=SignedImmutables linked from our contract's code page

oh, just seeing this

**Pull request merged**
