### PR TITLE
client/core: fix cancel match ntfn being active/new

### PR DESCRIPTION
**Pull request by chappjc**
This resolves https://github.com/decred/dcrdex/issues/2173.

When the match cards on the order details page became fully dynamic, a new match notification was added for the cancel match.  However, the match was sent as `Active=true` and with `Status=order.NewlyMatched`.  This does not agree with the matches that get listed by `(*Core).coreOrderFromMetaOrder` (which serves the `/api/order` and `/api/orders` endpoints) because they pull the match data from the DB, which was patched in the `*db.MetaMatch` when storing it.

This resolves the bug by using the `*db.MetaMatch` in `(*trackedTrade).negotiate` when constructing this match ntfn.

Side note: the `trackedTrade.matches` map intentionally does not include cancel matches, and thus the `core.Order`s returned by `(*trackedTrade).coreOrderInternal` do not include the cancel matches in the `Matches []*core.Match` slice field.  It may or may not be worth resolving this inconsistency with `(*Core).coreOrderFromMetaOrder` that includes cancel matches.

### CODE REVIEW

**Comment by norwnd** [comment]
> Note sure if this resolves the booked/settling case reported in @norwnd's comment https://github.com/decred/dcrdex/issues/2173#issuecomment-1445723166, but I confirmed this resolves the canceled/settling issue.

I'll try to reproduce it again with/without changes in this PR a bit later. And let you know.

**Review by JoeGruffins — APPROVED** [review]
I found it rather difficult to reproduce the issue. I could if I switched between markets with a cancel order, and more orders, but I don't see it with these changes.

Maybe because simnet times are faster.

**Comment by chappjc** [comment]
https://user-images.githubusercontent.com/9373513/221742248-98e8de6f-0a61-4559-8518-454db73bb5f2.mp4

**Comment by JoeGruffins** [comment]
I see on master:

https://user-images.githubusercontent.com/34998433/221749367-e3d776ba-c349-49fc-9adb-31b1079cdb24.mp4

**Comment by chappjc** [comment]
Call me baffled.  This effect happens every time for me.  Most of the time it stays with settled too

**Comment by chappjc** [comment]
Happens on mainnet for me too. Below it stayed that way:

image

The previous screen video was testnet at commit https://github.com/decred/dcrdex/pull/2181/commits/9d7f92c5a60645821a2a5fdf235ee617714239bb

Regardless of the reproduction, the root cause is fairly clear from the code.  Hopefully this also resolves the `booked/settling` issue observed by @norwnd.

**Comment by JoeGruffins** [comment]
I was indeed able to reproduce on master on mainnet just now. Just making orders and canceling.

**Review by buck54321 — APPROVED** [review]

**Pull request merged**
