### PR TITLE
client,testing: bumped dashcore minimum version -> 21.0.0

### PR DESCRIPTION
**Pull request by dev-warrior777**
Tested regtest livetest. This is major version upgrade
	which has breaking changes.

### CODE REVIEW

**Comment by dev-warrior777** [comment]
[v21.0.0 binaries](https://github.com/dashpay/dash/releases/tag/v21.0.0)

**Comment by buck54321** [comment]
If this has breaking changes, why is only the version number changed? Are you saying that dashd nodes < v21 will be forked off?

**Comment by dev-warrior777** [comment]
> If this has breaking changes, why is only the version number changed? Are you saying that dashd nodes < v21 will be forked off?



> his has breaking changes, why is only the version number changed? Are you saying that dashd nodes < v21 will be forked off?

Eventually forked off yes .. it has now been upgraded to by 85% Of the network. It is a major version change from 20.x.x which is what we had.

And there is yet [another one](https://github.com/dashpay/dash/releases/tag/v21.1.0) which is a minor version change. No breaking changes (for non-master-nodes) Today: 08 August 2024

**Comment by dev-warrior777** [comment]
This is what we have now.

_From DCRDEX  v1.0.0-rc2_

`minNetworkVersion       = 200101 // Dash v20.1.1`

This had breaking changes to RPC's which luckily only broke our harness

**Comment by dev-warrior777** [comment]
_checked also with `theDesertLynx`_

"DashCore v21.0 is a major release and a mandatory upgrade for all masternodes. Miners and users are recommended to upgrade, but DashCore v20.1.1 and v20.0.4 have been tested for compatibility with the new version."

So we good! I will close after you have had a chance to read

**Pull request closed without merging**
