### PR TITLE
UI: use Bison Wallet favicon

### PR DESCRIPTION
**Pull request by buck54321**
image

### CODE REVIEW

**Comment by buck54321** [comment]
I'm open to criticism here. People have said that this doesn't look much like a horn. I'm a little too deep to unsee a horn, I think. Bisons are hard to render at 16x16.

**Comment by exitus1** [comment]
> I'm open to criticism here. People have said that this doesn't look much like a horn. I'm a little too deep to unsee a horn, I think. Bisons are hard to render at 16x16.

The icon is small, so it's difficult to distinguish what it is. My recommendation would be to use:

bisonw-256

**Comment by pubpete** [comment]
I agree with the little bison logo if that works.

**Comment by buck54321** [comment]
image

**Comment by exitus1** [comment]
> image

Looks good. Also don't forget the tray icon

**Comment by pubpete** [comment]
> > image
> 
> Looks good. Also don't forget the tray icon

Also, don’t to add “Bison Wallet” to the UI. :)

**Comment by buck54321** [comment]
> Looks good. Also don't forget the tray icon

Really? I find it hard to tell what that is at that resolution.

**Comment by martonp** [comment]
I think the bison looks better as well. You can't really tell what the favicon is either, but you know what it is because you've seen the larger version.

**Review by martonp — APPROVED** [review]

**Comment by buck54321** [comment]
I concede defeat.

**Pull request merged**
