### PR TITLE
core: Add `ExpiredBonds` field to `ExchangeAuth`

### PR DESCRIPTION
**Pull request by ukane-philemon**
This PR adds a core method that exposes expired bonds for all connected dex servers.

### CODE REVIEW

**Review by JoeGruffins — APPROVED** [review]

**Review by buck54321 — CHANGES_REQUESTED** [review]
Please consider https://github.com/buck54321/dcrdex/compare/2a1b09b...buck54321:dcrdex:expiredbonds

1. Promotes the `dexAcctBondState.expiredBonds` field to the exported `ExchangeAuth`, which means the bond info is in the `Exchange` and the `User`.
2. If `ExpiredBonds` is still needed, `dexBondConfig -> bondStateOfDEX` is a little heavy-handed. Simpler this way.

I don't know exactly what the use case is, but there are also notifications for bond confirmations, expiration, and refund.

**Comment by ukane-philemon** [comment]
> Promotes the dexAcctBondState.expiredBonds field to the exported ExchangeAuth, which means the bond info is in the Exchange and the User.

Okay. I initially skipped promoting that field as it'll make `ExpiredBondsPendingRefund` kinda redundant.

Okay to remove `ExpiredBondsPendingRefund`?

**Comment by buck54321** [comment]
> The use case is that we have expired bonds when core starts but the user has right?yet to log in. Some consumers of `Core` might need to know this information to perform special actions(preparing the external wallet for `Core` use).

With the promoted field, everything will be in `User`. Still need the new method?

**Comment by ukane-philemon** [comment]
> Still need the new method?

I'll promote that field.

I was asking if it's okay to remove `ExpiredBondsPendingRefund` in this PR since it'll be redundant.

**Comment by buck54321** [comment]
> I was asking if it's okay to remove `ExpiredBondsPendingRefund` in this PR since it'll be redundant.

Go for it. You'll have to update registry.ts and dexsettings.ts.

**Review by buck54321 — APPROVED** [review]

**Pull request merged**
