### PR TITLE
client/comms: return descriptive error for ws conn cert issues

### LINKED ISSUE #225: dexc: no warning or error if dex url lacks entry in certs.json
If ~/.dexc/certs.json lacks and entry for the dex specified on the web interface, it has an error that does not indicate the missing entry in certs.json:

> [ERR] WEB: preregister error: Error initalizing websocket connection: x509: certificate signed by unknown authority

image

Ideally `dexc` would indicate that the dex url didn't have a cert specified.

### PR DESCRIPTION
**Pull request by itswisdomagain**
Return **`certificate required`** or **`invalid certificate`** error message for cert-related connection issues.
Resolve #225.

_With no cert provided_
Screenshot 2020-05-19 at 10 51 59 PM

_With invalid cert provided_
Screenshot 2020-05-18 at 9 59 59 PM

### CODE REVIEW

**Comment by itswisdomagain** [comment]
My tests reveal that the `certificate signed by unknown authority` error may be returned even if a cert is provided - when the cert is actually unknown to the DEX server.

Latest commit ensures that `certificate required` error is only returned if no cert was actually provided while returning `invalid cert` errors when a cert is provided.

**Comment by chappjc** [comment]
> `certificate signed by unknown authority` error may be returned even if a cert is provided - when the cert is actually unknown to the DEX server.

**Comment by chappjc** [comment]
Oops, didn't mean to close.  I was going to say that the comment "cert is actually unknown to the DEX server" doesn't jive with my understanding of how the tls certificate is used.  The client takes user provided certificate and adds to their list of trusted/root certificates, which makes it an authority.  Then on TLS negotiation with the server, the client will try to verify the certificate it gets from the server.

There are two main ways to fail this validation:
- missing trusted certificate in the client's cert store
- mismatched server name

So if you are providing the certificate, that means it either no longer matches the server's key/cert pair or it is the right certificate for the server's key but the server name is incorrect.  We can improve this by parsing all the DNS and IP entries for "X509v3 Subject Alternative Name" in the provided cert file and maybe from what we get from the server for verification, but I don't know how to access the latter.

**Comment by chappjc** [comment]
Anyway, the message to show in the case where a cert is provided by verification still fails is more nuanced.

I'm happy with "`certificate required` error is only returned if no cert was actually provided while returning invalid cert errors when a cert is provided"

**Comment by buck54321** [comment]
The actual displayed error text can drop the `getfee error: Error initializing websocket connection:` part. It should just say `certificate required` or `invalid certificate`. Can you somehow catch the error in **webserver** and replace it?

**Comment by itswisdomagain** [comment]
> I was going to say that the comment "cert is actually unknown to the DEX server" doesn't jive with my understanding of how the tls certificate is used. 

Right, looked (unsuccessfully) for a better way to put that. I meant the cert provided does not match the server's key/cert pair.

**Comment by chappjc** [comment]
Related to the ServerName point I mentioned in [my comment above](https://github.com/decred/dcrdex/pull/380#issuecomment-631498109), similar issue with the wallet connection.

Using `:19567`, it does not try to connect with localhost or 127.0.0.1, so it has a TLS error even though it is the correct cert:

```
[INF] CORE[dcr]: Setting up new DCR wallet at :19567 with TLS certificate "/home/jon/dextest/dcr/alpha/rpc.cert".
[ERR] WEB: error creating dcr wallet: Error connecting wallet: Decred Wallet connect error: tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config
```

Using `localhost:19567` works:

```
[TRC] CORE: wallet status requested for unknown asset 42 -> dcr
[INF] CORE[dcr]: Setting up new DCR wallet at localhost:19567 with TLS certificate "/home/jon/dextest/dcr/alpha/rpc.cert".
[INF] CORE: Created dcr wallet. Account "default" balance available = 4959693683625 / locked = 0, Deposit address = SsfWraUBDUtU2dKAhBAYcb8HVTEupAnj9ta
```

Because:

```
$   openssl x509 -in /home/jon/dextest/dcr/alpha/rpc.cert -text -noout | grep -A 1 "Subject Alternative Name"
            X509v3 Subject Alternative Name: 
                DNS:monkey-cube, DNS:localhost, IP Address:127.0.0.1, 
IP Address:0:0:0:0:0:0:0:1, IP Address:....
```

**Comment by itswisdomagain** [comment]
> The actual displayed error text can drop the `getfee error: Error initializing websocket connection:` part. It should just say `certificate required` or `invalid certificate`. Can you somehow catch the error in **webserver** and replace it?

I'll work something out. Similar pattern can probably subsequently be used for displaying well-formatted GUI error messages.

**Comment by itswisdomagain** [comment]
Regarding...
> ...if you are providing the certificate, that means it either no longer matches the server's key/cert pair or it is the right certificate for the server's key but the server name is incorrect.

The latter _seems_ to be properly handled for DEX connections. Using domain name rather than IP or "localhost", I get `certificate is valid for ubuntu-s, localhost, not domain.com`. I get this message when connecting to a domain whether or not I upload a cert file, so I guess something's amiss there.

On the other hand, `invalid cert` error is currently only displayed when ws connection returns `x509.UnknownAuthorityError` **_and_** the user provided a certificate. I believe getting an `x509.UnknownAuthorityError` when the user provided a certificate implies the certificate does not match the server's key/cert pair.

Can we improve this any further?

**Comment by chappjc** [comment]
OK, so if the server name mismatches, it already shows a sensible error (`certificate is valid for ..., not domain.com`)?  While `x509.UnknownAuthorityError` definitely indicates it's not just the server name, but a key/cert mismatch?  **And** the GUI error in red no longer starts with "getfee error: ...", and is instead just "certificate required" or "invalid certificate?"  If that's all accurate, I'd say this is good to go.

**Pull request merged**
