### PR TITLE
gomod: Update neutrino.

### PR DESCRIPTION
**Pull request by JoeGruffins**
This fixes a block cannot be found sync error for btc spv.

I was finally able to sync on testnet and mainnet without issue with this update.

Part of #2899

### CODE REVIEW

**Comment by JoeGruffins** [comment]
It appears the error does still happen sometimes... But less. And stopping, starting the wallet gets it going again.

**Comment by ukane-philemon** [comment]
Able to figure out the root cause? Is it something that requires an upstream fix?

**Comment by JoeGruffins** [comment]
> Able to figure out the root cause? Is it something that requires an upstream fix?

They seem to be changing a lot of stuff with peers. It looks like they are busy ironing out the bugs though.

**Comment by ukane-philemon** [comment]
Okay

**Pull request merged**
