### PR TITLE
client/webserver/site: dev dep updates with slash-div bootstrap fix

### PR DESCRIPTION
**Pull request by chappjc**
This is intended to be a final bump of node devDependencies before the v0.4 release.

A separate commit changes the Node.js versions used in CI to 16 (LTS) and 17 (current) since v16 transitioned from current to LTS in https://nodejs.org/en/blog/release/v16.13.0/

Of note is the update of bootstrap from 4.6.0 to 4.6.1, since this [includes a fix for the slew of slash-div warnings](https://github.com/twbs/bootstrap/pull/34571) from sass dart.

Minor bumps:
- @babel/{core,eslint-parser,preset-env}: 7.15.0 -> 7.16.5
- css-loader: 6.2.0 -> 6.5.1
- css-minimizer-webpack-plugin: 3.0.2 -> 3.3.1
- eslint-plugin-import 2.24.2 -> 2.25.3
- eslint-plugin-promise: 5.1.0 -> 5.2.0
- eslint-webpack-plugin: 3.0.1 -> 3.1.1
- mini-css-extract-plugin: 2.2.0 -> 2.4.5
- sass: 1.38.1- -> 1.45.1
- sass-loader: 12.1.0 -> 12.4.0
- stylelint-webpack-plugin: 3.0.1 -> 3.1.0
- webpack: 5.51.1 -> 5.65.0
- webpack-bundle-analyzer: 4.4.2 -> 4.5.0
- webpack-cli: 4.8.0 -> 4.9.1

Patch:
- babel-loader: 8.2.2 ->8.2.3
- bootstrap: 4.6.0 -> 4.6.1

Also, clean-webpack-plugin went from "4.0.0-alpha.0" to just 4.0.0, but these reference the same actual revision, just a new tag.

### CODE REVIEW

**Comment by buck54321** [comment]
For reference: https://sass-lang.com/documentation/breaking-changes/slash-div

**Comment by chappjc** [comment]
Removed from 0.4 milestone as we're gonna skip this for RC1, but we can reconsider before final release if this shows no issues on master.

**Review by JoeGruffins — APPROVED** [review]
I think I'm on node v14.18.2 forever because decrediton wants that, but building fine.

**Comment by chappjc** [comment]
> I think I'm on node v14.18.2 forever because decrediton wants that, but building fine.

Decrediton just moved to Electron 15 (Node.js v16.5), we should jive with that now. https://github.com/decred/decrediton/pull/3571

**Comment by chappjc** [comment]
This is working fine for me when rebased on release-v0.4, but we don't have to use it there yet.
For now just merging on master for more use.

**Pull request merged**
