### PR TITLE
client/eth: provide default providers for eth and polygon

### LINKED ISSUE #2704: client/{polygon,eth}: subscription-free providers options needed
The only thing preventing "one-click" wallet creation for Polygon/Ethereum, or config-free wallet creation during app initialization, is the need to specify an infrastructure provider. But there are free and seemingly reliable provider endpoints, albeit rate limited.

Is it possible to offer configuration-free Polygon and Ethereum wallets using free endpoints? The the free endpoints have sufficient rate limits for our needs? We need a deep look at the available providers, their long-term stability, and their rate limits as compared to our usage requirements.

### PR DESCRIPTION
**Pull request by buck54321**
closes #2704

### CODE REVIEW

**Comment by buck54321** [comment]
Changed Ethereum testnet network to Sepolia because Goerli is being phased out and I'm seeing outdated blocks from some providers. 

You can get 0.5 Sepolia ETH every 24 hours from Infura or Alchemy with an account.
Get 10 Sepolia USDC from https://faucet.circle.com/

Don't forget to update your ~/dextest/credentials.json

**Comment by JoeGruffins** [comment]
I've started syncing a node on sepolia...

**Review by martonp — COMMENTED** [review]
I think the UI should somehow encourage people to sign up for a provider with an account as they're probably more reliable. Also, I think people should know which providers they're connecting to. Maybe show a list of these defaults with checkboxes next to them, and allow them to uncheck some if they would like?

**Comment by buck54321** [comment]
> I think the UI should somehow encourage people to sign up for a provider with an account as they're probably more reliable. Also, I think people should know which providers they're connecting to. Maybe show a list of these defaults with checkboxes next to them, and allow them to uncheck some if they would like?

I had similar thoughts, but our main goal is to minimize friction setting up wallets for new users. Creating an Ethereum or Polygon wallet is just a checkmark during initialization now. 

I still agree that we should find a way to encourage users to specify their own provider(s), even though e.g. MetaMask does no such thing.

**Comment by martonp** [comment]
During initialization, if they select a polygon/eth wallet, there could be another screen which lists the providers, and they are all selected by default. This screen would also have some text saying that for better reliability, you should create a free account on alchemy, infura, or whatever. There's not really much friction, they can just click the submit button and skip past it. It could be a future PR though.. it's fine like this for now too. I'm just worried about how reliable these free accountless RPCs are.

**Comment by buck54321** [comment]
@martonp I put some prompts around. What do ya think?

**Comment by martonp** [comment]
@buck54321 I think it looks good. Maybe add a tooltip next to it with an little explanation that there are defaults, but a custom one would be more reliable.

**Comment by JoeGruffins** [comment]
Clicking on "Add a custom API provider" for tokens blinks and does nothing.

**Pull request merged**
