### PR TITLE
multi: btcsuite and go-ethereum updates

### PR DESCRIPTION
**Pull request by chappjc**
A number of updates in the btcsuite universe have created new sub-modules, and introduced breaking changes to several packages.  This work adapts to the changes:

- `btcec/v2` was created as a new module.  The was important so that go-ethereum, which imports btcec for it's no-cgo `crypto` package, could break free from the btcd mega-module that did _not_ follow semantic import versioning, creating challenges with breaking changes with minor version updates.  The migration of `go-ethereum/crypto` to the new `btcec/v2` module was done in https://github.com/ethereum/go-ethereum/pull/24533
- Since `btcec/v2` is primarily type aliases into `dcrd/secp256k1/v4`, a number of syntax changes are made similar to `dcrec`
- `btcutil` was moved from it's own repo (github.com/btcsuite/btcutil) into a new submodule in the btcd repo (github.com/btcsuite/btcd/btcutil)
- `txscript` was updated for taproot support, and there were a few breaking changes.  Namely, `NewTxSigHashes` requires a `PrevOutFetcher` for taproot support, and `ExtractPkScriptAddrs` no longer returns an error for invalid/non-standard scripts.
- `github.com/btcsuite/btcwallet/wallet` was updated to use the new `txscript` and there was a syntax change to `wallet.(*Wallet).SendOutputs`
- `github.com/btcsuite/btcwallet` itself was updated for the above changes

There will be more btcsuite module changes in the near future, including the introduction of `wire`, `chaincfg`, `btcutil/address`, and `txscript` modules to `btcd` (see https://github.com/btcsuite/btcd/pull/1825), as well as corresponding updates to `btcwallet`, but this starts the processes and moves to a `go-ethereum` version that does not require the `btcd` mega-module that is not friendly to Go consumers.

### CODE REVIEW

**Comment by JoeGruffins** [comment]
Comment has `go-ethereum` in it, which is probably not the right thing?

**Comment by chappjc** [comment]
The go-ethereum update to the 1.10.17 pre-release is related to the btcec/v2 update since go-ethereum was using the btcd module.  This is what I'm describing in the first bullet.

**Comment by JoeGruffins** [comment]
Oh, I'm sorry. I guess I have a reading problem. The first bullet explained it.

**Comment by chappjc** [comment]
There will be more to come with https://github.com/btcsuite/btcd/pull/1825 and other module changes in the btcsuite repos, but this is working as is to allow us to freely update both btcsuite and go-ethereum modules.

**Review by JoeGruffins — APPROVED** [review]

**Comment by chappjc** [comment]
Will update the go-ethereum require to use https://github.com/ethereum/go-ethereum/pull/24649

**Review by buck54321 — CHANGES_REQUESTED** [review]
I can't get the core live tests to pass (passing on master), but maybe just need a rebase? Everything else seems good to go.

Specifically, running `TestNoMakerRedeem`, first I got a 

```
trade_simnet_test.go:937: client 2 reported 1 incomplete trades for order b4aefa89 after 2m0s
```
then subsequent tests gave 

```
trade_simnet_test.go:299: error starting clients: dcr wallet authentication error: -4: encryption/decryption error: account is not encrypted with a unique passphrase
```

**Comment by chappjc** [comment]
Rebased but not re-tested.

**Review by buck54321 — APPROVED** [review]
Testing well. lgtm

**Comment by chappjc** [comment]
Oh fft go-ethereum 1.10.18 was released this morning. :facepalm:

**Pull request merged**
