### PR TITLE
multi server: millisecond order times

### PR DESCRIPTION
**Pull request by chappjc**
Order time stamps presently have second resolution, but millisecond resolution may be desirable for both order time stamps and epoch duration.  This starts the changes necessary to make millisecond order time stamps.

### CODE REVIEW

**Comment by buck54321** [comment]
These changes help ensure the matching algorithm is fair. Combined with a tertiary sorting criteria, probably lexicographic sorting by order ID, the pair of changes provides a full solution to the problem of unspecified behavior during matches when there are identical timestamps and rates for two or more standing orders.

Specification updates will be needed separately.

**Comment by buck54321** [comment]
Did you want to pick up the timestamps in the `Swapper` and `AuthManager` here? I guess those could technically stay in seconds, but I'd prefer to use the same units throughout.

**Comment by chappjc** [comment]
Yup, I'll be getting to that today. Just finishing up somework on cspp in dcrdata...

**Comment by chappjc** [comment]
`swap` and `auth` updated too.  @buck54321 TestBroadcastTimeouts fails intermittently with `swap_test.go:1324: no penalty at step 0` but I don't see the cause.

**Pull request merged**
