### PR TITLE
eth/multirpc: add timeouts to requests

### PR DESCRIPTION
**Pull request by buck54321**
Re #2045.

### CODE REVIEW

**Comment by chappjc** [comment]
Nice.  Do you happen to know what default or built-in rpcclient timeout I was hitting in https://github.com/decred/dcrdex/issues/2045?  I can't find any timeout in geth's `httpConn` that it would have been using for the requests.
Is that the issue you meant to reference?  I don't see the link with PR 2025.

**Comment by buck54321** [comment]
Yes. Typo. Should have been #2045. Edited.

> Do you happen to know what default or built-in rpcclient timeout I was hitting in https://github.com/decred/dcrdex/issues/2045?

Hmm. I was really trying to address the hang at `ChainID` and carrying that through, but I similarly could find no timeouts in geth for http requests, so I'm not sure where the context deadline errors are coming from. I'll take another look.

**Comment by JoeGruffins** [comment]
> Nice. Do you happen to know what default or built-in rpcclient timeout I was hitting in https://github.com/decred/dcrdex/issues/2045? I can't find any timeout in geth's httpConn that it would have been using for the requests.

Could it be these default timeouts? https://github.com/ethereum/go-ethereum/blob/a35b654f25fdac518d5775b55aa064025040b01a/rpc/http.go#L114-L121

**Review by JoeGruffins — APPROVED** [review]
Looks right and working well.

**Comment by chappjc** [comment]
> > Nice. Do you happen to know what default or built-in rpcclient timeout I was hitting in #2045? I can't find any timeout in geth's httpConn that it would have been using for the requests.
> 
> Could it be these default timeouts? https://github.com/ethereum/go-ethereum/blob/a35b654f25fdac518d5775b55aa064025040b01a/rpc/http.go#L114-L121

I had followed those, and they seem only to be used when geth makes it's RPC *server*.  No matter.

**Review by chappjc — APPROVED** [review]

**Pull request merged**
