### PR TITLE
ui: display your orders rate in header

### PR DESCRIPTION
**Pull request by norwnd**
Resolves https://github.com/decred/dcrdex/issues/2254.

Rate fits reasonably well with the longest `canceled/settling` status and max rate step we currently have = 6

image

### CODE REVIEW

**Comment by norwnd** [comment]
Note, `fourSigFigs` results in non-precise rate shown in "Your Orders" section (should be `1.000001`, not `1`):

image

Is it something we want to fix (assuming it's possible to do without using external decimal-arithmetic libs) ? Reading through [this discussion](https://github.com/decred/dcrdex/pull/2208#discussion_r1129324708) I've got a feeling that we don't care about this when displaying spot price (or similar). For order  rate however user might be somewhat uneasy to see such rounding imo.

**Review by chappjc — APPROVED** [review]

**Comment by buck54321** [comment]
I draw a distinction between numerical "display" values and "data" values. Display values, such as the market statistics shown at the top of the markets view, can employ rounding or truncation and should use significant figures to make values "pretty". Data values, such as order data, should not employ rounding, and should use e.g. `UnitInfo.Conventional.ConversionFactor` to decide how many digits/decimals to display.

**Comment by norwnd** [comment]
To resolve the issue mentioned in https://github.com/decred/dcrdex/pull/2281#issuecomment-1492852434 I'll need to apply similar fix implemented in https://github.com/decred/dcrdex/pull/2278#issuecomment-1500847677, for rate included in "header" in this PR.

**Comment by chappjc** [comment]
Can we just get this merged with the current reasonable solution (perhaps just forcing at least one decimal)?  https://github.com/decred/dcrdex/pull/2278#issuecomment-1500847677 may contain the resolution, but is is a can of worms and will preculde this small change from landing in 0.6.1

**Comment by chappjc** [comment]
1.000001 is a rate that isn't likely to be practical (too much precision), so I'm inclined to just merge this as-is if there's not a quick resolution tomorrow.
Or for the purposes of this PR (without https://github.com/decred/dcrdex/pull/2278#issuecomment-1500847677 and strict rate step observation), we could use `Doc.formatFiveSigFigs(rate)` instead of  of `fourSigFigs(rate)`.

**Comment by norwnd** [comment]
> 1.000001 is a rate that isn't likely to be practical (too much precision), so I'm inclined to just merge this as-is if there's not a quick resolution tomorrow.

I'd rather not try to come up with yet another way to handle this specific case (and I don't see anything simple we can do here), so I'd wait until https://github.com/decred/dcrdex/pull/2278#issuecomment-1500847677 is ready,

but merging as is is also fine, I believe, because we show this trimmed rate in "details" anyway, so showing in header as well doesn't really break anything.

**Comment by chappjc** [comment]
Right it's no deviation from existing convention.  I'm asking for @buck54321 call though regarding asap merge resolution.

**Review by buck54321 — APPROVED** [review]

**Pull request merged**
