### PR TITLE
multi: add dcr wallet client.

### PR DESCRIPTION
**Pull request by dnldd**
Work towards #36.

### CODE REVIEW

**Comment by buck54321** [comment]
Consider renaming this PR to "wallet: add contract script functions" so we can get it in. I don't want to block wallet development while you're working on DEX API pieces.

**Comment by dnldd** [comment]
will be adding to the initial with new commits.

**Comment by buck54321** [comment]
Definitely on the right track, though the `Client` will need quite a bit of work still. I'm going to push the BTC wallet client in a couple days, and there will be substantial changes needed for them to have a common functional interface. I can see two ways of handling this. 

1. Let's get this PR reviewed and merged, and I'll adapt the `Client` separately. 

2. Leave this PR idle for a couple days and we can look at the two wallets side-by-side. 

I'm leaning towards #1, but I'm not crazy about merging the `Client` in it's current state. What do you think, @chappjc?

**Comment by chappjc** [comment]
@buck54321 Either was is OK with me, although leaving this opened until the btc wallet client is up might benefit both PRs, although that's likely to result in more iterations to get them both merged.  Your call.

**Comment by buck54321** [comment]
I think we should merge it after review. Let's not fret too much about tests, since they would likely need substantial rewrites after the interface is reworked anyway.

**Pull request merged**
