### PR TITLE
testing: add miners to harnesses

### PR DESCRIPTION
**Pull request by buck54321**
Just a thought. We don't have to auto-mine, and I haven't considered how this might affect others tests, but it seems simple enough and I think we'll want something reasonable for bond maintenance.

### CODE REVIEW

**Comment by chappjc** [comment]
Seems reasonable to me.  The rotateBonds method is called every 20 seconds, so I found on simnet that I had to set me watch interval to be less than that (settled on 15) otherwise you occasionally rotate too late and get a tier drop.

**Comment by ukane-philemon** [comment]
Nice. Makes sense and is a useful addition.

**Comment by buck54321** [comment]
E2E tests seem to be working. Loadbot runs a miner that targets 1 block per roughly two epochs. If it's important to maintain that target (I don't think it is), we can always shut the miners down.

**Review by JoeGruffins — APPROVED** [review]
Probably fine. Can always turn them off. Some tests mine though... I feel like dcr gets funky if you try to mine from two places. But again can just turn off and let the test mine.

The dcr harness goes to the mining session rather than the ctrl-harness after these changes.

**Comment by JoeGruffins** [comment]
The dcr harness still defaults to a different session.

**Pull request merged**
