### PR TITLE
multi: go mod tidy & gofmt

### PR DESCRIPTION
**Pull request by dajohi**

### CODE REVIEW

**Comment by chappjc** [comment]
Thanks for the cleanup.

The go mods and sums are super pointless at this stage though.  I kinda wish we were working in GOPATH mod with GOMODULE=off since everything is just replaced everywhere.

**Comment by jrick** [comment]
why not make the entire repo a single module (no submodules?)

**Comment by chappjc** [comment]
@jrick That's a good idea.
@dajohi Wanna do that for us and see if it works out?

**Comment by jrick** [comment]
you could grab decred.org/dcrdex as the module name at this point too.

**Comment by dajohi** [comment]
replaced by #89

**Pull request closed without merging**
